### ISSUE TITLE
Pivy's QuarterWidget: Not properly handled (or missed) mouse click events in examples 13.4 and 13.5

### ISSUE THREAD

**Issue by InventorMentor** [looooo/pivy#10]
Issue found and test cases:
Running example 13.4.Gate.py, clicking the left mouse button repeatedly is expected to toggle duck motion, howevever, often in a quick sequence of left mouse clicks they do not get handled /  are being missed / have no visual effect. (However, there do not seem to be any missed mouse clicks when alternating between clicking the left and right mouse button in these python examples.) The same issue also could be produced with example 13.5.Boolean.py as a second test case. Running the corresponding native C++ examples 13.4 and 13.5, however, I was unable to produce this issue. Therefore, I reckon the issue is with Pivy.

Test environments where this issue was found:
- 32-bit Debian 7, default packages: Python 2.7.3, Coin3D 3.1.3, Pivy 0.5.0
- 64-bit Windows 10, 64-bit Python 3.6.1, Coin3D 4.0.0a, Pivy 0.6.0

Maybe you can produce and confirm this issue in your environment, too. Many thanks!

**Comment by looooo** [comment]
I think this behavior is related to double clicks. For me a double click doesn't gives this result:
`1, 0, 0` which means `button-down, button-up, button-up`

you can try this by adding this line inside of the callback function:
```python
print(event.getState())
```

Is there a online-source for the equivalent c++ examples?

**Comment by looooo** [comment]
just tested this with FreeCAD, and there no missing button down occurs. So maybe this is a problem with quarter... Are you using quarter or sogui?

**Comment by InventorMentor** [comment]
Many thanks for attempting to reproduce this issue in your environment. 

Since Pivy's SoQt wrapper has not been ported to Python3, yet, I'm currently using
Quarter-1.0.0 with Pivy 0.6.0 under Python3/Windows10. To this end, I did not see
a problem with using Quarter instead of SoQt, since it seems to be a more modern
GUI binding of Coin to Qt, anyway. I'm aware of the more flexible (configurable)
event system of Quarter but have not learned yet how to modify it via its
ScXML-based configuration system.

Having tested the native C++ example 13.4 as a baseline for my expectations,
I was able to run example 13.4 successfully with both Qt-GUI bindings, SoQt-1.5.0
and Quarter-1.0.0, without missing any mouse clicks toggeling the duck's motion.

However, when testing 13.4.Gate.py with both Python3/Pivy/Quarter (this branch)
on Windows10 and also under 32-bit Debian7 with both Python2/Pivy/SoQt and
Python2/Pivy/Quarter, I can easily produce the missing mouse clicks (also when
using Quarter through SoGui).

I don't have to left-click with a particular high frequency for producing this
issue, one left-click every other second should be fast enough, The issue
does not occur to me every time, however, often (25% or more of the clicks),
but never, if I click a sequence alternatingly switching between the left
and right mouse button every other click instead of just a sequence of
left-clicks. With a sequence of alternating left/right mouse button clicks
I'm can not reproduce this issue even with a click frequency greater than 1 Hz). 

Therefore, I don't think that this is an issue related to Coin, SoQt, or Quarter
but rather a problem with my Python-binding or my example code (e.g. not
configuring the ScXML for Quarter correctly; however, in the working C++ example
using Quarter I also don't do any ScXML configuration either and just use the
defaults as in Quarter's minimal.cpp example).

It is interesting to learn that you could not reproduce this issue in your own
test environment. Therefore, any ideas how I can further narrow down this issue
would be grately appreciated. Many thanks!

**Comment by looooo** [comment]
>It is interesting to learn that you could not reproduce this issue in your own
test environment. Therefore, any ideas how I can further narrow down this issue
would be grately appreciated. Many thanks!

I just wanted to mention, that FreeCAD uses a c++ implementation of quarter.

**Comment by InventorMentor** [comment]
N.B.: A work around to this issue with Pivy's QuarterWidget is using SoQt instead:
With the availability of commit a0c3e84, SoQt port (#17), I re-tested both examples 13.4 and 13.5 with SoQt instead of Pivy's QuarterWidget and now the left mouse click behaviour is as expected (identical to running the corresponding C++ examples: in a long sequence of left mouse clicks, there were no missed left mouse clicks; every single left mouse click did toggle the duck's motion, even at high click frequencies above 1 Hz).
