### ISSUE TITLE
example examiner_embed4.py not working with soqt (PySide port)

### ISSUE THREAD

**Issue by InventorMentor** [looooo/pivy#19]
Using latest commit a0c3e84, Soqt port (#17) , replacing line 34 in example examiner_embed4.py
`apply(QMainWindow.__init__, (self,) + args)`
with
`super(self.__class__, self).__init__()`
is not enough to fix this example. [Nevertheless, this example works for me using a previous version of pivy  (Debian 7, pivy-0.5.0, PyQt4).] 

With the current version of pivy's SoQt-binding (PySide port), there seems to be a type resolution problem with resolving the correct overloaded C++ constructor creating a new instance of SoQtExaminerViewer when attempting to embed it in a PySide widget hierarchy.

```
  File "C:/pivy-0.6.2/examples/examiner_embed4.py", line 127, in <module>
    main()
  File "C:/pivy-0.6.2/examples/examiner_embed4.py", line 116, in <module>
    vp = EmbeddedWindow()
  File "C:/pivy-0.6.2/examples/examiner_embed4.py", line 93, in <module>
    self.exam = SoQtExaminerViewer(self.examiner)
  File "C:\python-3.6.1.amd64\Lib\site-packages\pivy\gui\soqt.py", line 3200, in __init__
    this = _soqt.new_SoQtExaminerViewer(*args)
builtins.NotImplementedError: Wrong number or type of arguments for overloaded function 'new_SoQtExaminerViewer'.
  Possible C/C++ prototypes are:
    SoQtExaminerViewer::SoQtExaminerViewer(QWidget *,char const *,SbBool,SoQtFullViewer::BuildFlag,SoQtViewer::Type)
    SoQtExaminerViewer::SoQtExaminerViewer(QWidget *,char const *,SbBool,SoQtFullViewer::BuildFlag)
    SoQtExaminerViewer::SoQtExaminerViewer(QWidget *,char const *,SbBool)
    SoQtExaminerViewer::SoQtExaminerViewer(QWidget *,char const *)
    SoQtExaminerViewer::SoQtExaminerViewer(QWidget *)
    SoQtExaminerViewer::SoQtExaminerViewer()
```

**Comment by looooo** [comment]
The problem is that soqt needs shiboken. But shiboken can be available as `import Shiboken.shiboken` or directly as `import shiboken`. The latter is the correct way to import it and pip-version has a bug there.
Please try again with my latest commit. If your shiboken is directly located somewhere in sys.path this should work now.

**Comment by InventorMentor** [comment]
Many thanks for your quick advice ... to make your most recent  commit f722bc0 compilable , I had to insert a missing definition
`PyObject* shiboken = NULL;`
into function getShiboken(). However, to this end, I couldn't figure out how to fix Shiboken's pip install location under Windows, yet, and I had no luck with running examiner_embed4.py with the most recent commit. Does this actually work for you? (this example requires the fix in the line 34 calling the inherited constructor I posted above in order to function under Python3)

**Comment by InventorMentor** [comment]
Making shiboken directly importable to WinPython (as "import shiboken") by manually copying the contents of my pip installation python3.6.1amd64\lib\site-packages\Shiboken\*.* one folder up (living now directly under site-packages) now lets me successfully import shiboken, however, examiner_embed4.py still gives me the following error message when trying to run this example:
`TypeError: wrapInstance expected 2 arguments, got 0`

Could you please confirm whether examiner_embed4.py fails for you using PySide under py3 linux64 as well? Many thanks in advance! Best regards and whishes!

**Comment by InventorMentor** [comment]
Just one more finding: Using wheel PySide‑1.2.4‑cp36‑cp36m‑win_amd64.whl
from Chris Gohlke's repository of python wheels for Windows
http://www.lfd.uci.edu/~gohlke/pythonlibs/
I found that his PySide wheel already ships with shiboken. Therefore, it should not  be necessasry to download Shiboken seperately and build it manually on Windows.

`from PySide import shiboken`

just works fine for me. I've already tried and adapted Pivy's interfaces/soqt.i correspondingly,
however, I still receive the TypeError reported above. Therefore, I reckon issue #19 is not related to importing shiboken.

**Comment by InventorMentor** [comment]
Closing this, since FreeCAD uses its own C++ implementation of QuarterWidget.

**Comment by looooo** [comment]
are you going to use the free-cad viewer?

**Comment by InventorMentor** [comment]
No, I reckon my best bet is to focus on your SoQt-PySide port for now, since it is closest to full Inventor Mentor compatibility in Python 3 as far as I can tell. Neverthless, to this end, SoQtExaminerViewer is not wrapped with Shiboken as a PySide QWidget type (but as pivy.gui.soqt.SoQtExaminerViewer) and its constructor unfortunately does not accept other QWidgets created with PySide. Therefore, though most Inventor Mentor examples run fine with SoQt now, not having SoQtExaminerViewer embedable in a PySide application makes the current SoQt port unusable from a pure Pythpn application development point of view ...
