### ISSUE TITLE
[conda] example 7.2 not working because of missing simage library

### ISSUE THREAD

**Issue by looooo** [looooo/pivy#9]
```
Coin warning in SbImage::readFile(): The simage library is not available, can not import any images from disk.
Coin warning in SoTexture2::filenameSensorCB(): Image file 'brick.1.rgb' could not be read

```

**Comment by InventorMentor** [comment]
All texture depended examples (e.g. example 7.2 mentioned here) work for me once I have installed a compiled version of the simage shared library in my search patch (LD_LIBRARY_PATH on linux). Therefore, I don't think that this is an issue with Pivy (e.g. a missing wrapper for this libraray) but rather a dependency of Coin3D. Therefore, I propose to close this issue.

**Comment by looooo** [comment]
you are right. It was more a reminder for my self to create a conda-package for simage. I am currently trying to do so. Seems there is no one keeping this library uptodate. Got some problems with libtiff, libpng...

**Comment by looooo** [comment]
reminder:
pathc: in `simage/src/simage_png.c`: replace line 345 with  if (setjmp(png_jmpbuf(png_ptr))) {

**Comment by looooo** [comment]
reminder:
patch for soqt: 
- `CmakeList.txt`: Coin::Coin ->Coin
- a moc_ ... .icc is not available ->simple comment out that include
- an #include is wrong ad SoQtMaterialList.cpp needs additional ../common/.. directory in path
